# syntax=docker/dockerfile:1.5
FROM eclipse-temurin:11-jre-focal@sha256:c41afb26202af58e2ab0bc8c07552a18aaebb528fd00dec9beeb02f4c260e24e
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=true
LABEL org.opencontainers.image.source=https://github.com/aps831/workflows-testbed-docker
RUN mkdir /opt/app
COPY ./target/testbed-docker-*-jar-with-dependencies.jar /opt/app/testbed-docker.jar
CMD ["java", "-jar", "/opt/app/testbed-docker.jar"]
