# syntax=docker/dockerfile:1.5
FROM maven:3.8-openjdk-18@sha256:f22971fa3103b6a5145741dd80cc1660490bef93deb6400276c96dadf5bfd75f
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=true
ARG DOCKER_GROUP_ID

RUN groupadd -r -g $DOCKER_GROUP_ID docker && useradd -m -l -r -u 1000 -g docker maven
ENV MAVEN_CONFIG /home/maven/.m2
ENV MAVEN_OPTS -Duser.home=/home/maven

USER maven
WORKDIR /app
