# syntax=docker/dockerfile:1.5
FROM eclipse-temurin:19-jre-focal@sha256:4f646d9ba7737e089a937d7a40427f8757f366829a03937b37112e2db5264b54
ARG BUILDKIT_SBOM_SCAN_CONTEXT=true
ARG BUILDKIT_SBOM_SCAN_STAGE=true
LABEL org.opencontainers.image.source=https://github.com/aps831/workflows-testbed-docker
RUN mkdir /opt/app
COPY ./target/testbed-docker-*-jar-with-dependencies.jar /opt/app/testbed-docker.jar
CMD ["java", "-jar", "/opt/app/testbed-docker.jar"]
