---
name: Grype Image Scan Published
on:
  registry_package:
    types:
      - published
permissions:
  packages: read
jobs:
  scan:
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != 'latest' }}
    uses: aps831/workflows/.github/workflows/grype-image-scan-published.yaml@feat/image-scans
    with:
      owner: ${{ github.repository_owner }}
      name: ${{ github.event.registry_package.name }}
      tag: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
