---
name: Trivy Image Scan
on:
  schedule:
    - cron: "0 4 10 * *"
  registry_package:
    types:
      - published
jobs:
  scan:
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != 'latest'}}
    permissions:
      packages: read
    uses: aps831/workflows/.github/workflows/trivy-image-scan.yaml@feat/scanning-workflows
    with:
      owner: ${{ github.event.repository }}
      name: ${{ github.event.registry_package.name }}
      tag: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
