---
name: Trivy Image Scan
on:
  schedule:
    - cron: "0 0 22 * *"
  registry_package:
    types:
      - published
permissions:
  packages: read
jobs:
  scan:
    if: ${{ github.event.registry_package.package_version.container_metadata.tag.name != 'latest' }}
    uses: aps831/workflows/.github/workflows/trivy-image-scan.yaml@feat/scanning-workflows
    with:
      owner: ${{ github.repository_owner }}
      name: ${{ github.event.registry_package.name }}
      tag: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}
    secrets:
      ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
